FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY OnlineLibriary.sln .
COPY Data/Data.csproj ./Data/
COPY BusinessLogic/BusinessLogic.csproj ./BusinessLogic/
COPY OnlineLibriary.Tests/OnlineLibriary.Tests.csproj ./OnlineLibriary.Tests/
COPY API/API.csproj ./API/

RUN dotnet restore

COPY . .

RUN dotnet build -c Release -o /app/build/API

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish/API --no-restore

FROM base AS final
EXPOSE 5296
EXPOSE 7034
WORKDIR /app
COPY --from=publish /app/publish/API .

# Set the entry point
ENTRYPOINT ["dotnet", "API.dll"]